General grammar/English fixes
discord-buttons/discord-buttons pull request #115
Opened 2021-07-03 20:20 UTC by GodyFromDiscord

This is just a small PR to improve the quality of some sentences and terms used in the package, they provide a clearer understanding and make things look nicer in general. 

This is not a dig at anyone English, but seeing how popular the package is, it seems fitting to make things a nice upstream quality.

2021-07-04 07:39 UTC, xHyroM approved these changes

2021-07-04 12:08 UTC, AngeloCore requested changes

2021-07-04 12:08 UTC, AngeloCore commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
use `discord` not `Discord`

2021-07-04 12:08 UTC, AngeloCore commented on README.md
> +All of our Examples and button styles found in [examples.md]([http://](https://github.com/AngeloCore/discord-buttons/blob/main/examples.md)) and
our button styles is a typedef

2021-07-04 12:08 UTC, AngeloCore commented on src/index.js
> +if (version.includes('(')) version = version.join('').split('(').pop().split('');
Do you use prettier?

2021-07-04 12:08 UTC, AngeloCore commented on typings/index.d.ts
> +import Discord, {
use `discord` everywhere

2021-07-04 13:19 UTC, GodyFromDiscord commented on src/index.js
> +if (version.includes('(')) version = version.join('').split('(').pop().split('');
I do not

2021-07-04 13:20 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
No, this is the most common usage of importing the discord module.

2021-07-04 13:20 UTC, GodyFromDiscord commented on README.md
> +All of our Examples and button styles found in [examples.md]([http://](https://github.com/AngeloCore/discord-buttons/blob/main/examples.md)) and
Nevertheless the grammar is wrong with the capilisation regardless of its type

2021-07-04 13:35 UTC, JackCrispy commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
most common usage is not always the most correct way to format and use code.

2021-07-05 16:16 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
In this case, yes it is, Discord itself is a proper noun, meaning it should be capitalised, similar to the discord.js docs when importing the client, the proper noun usage of Discord is used. A lot of examples that work with the module and require it, use capitalisation, it's simple grammar which is what the pull requests is about, so take it with a pinch of salt. It should be capitalised per reasoning of this pull request.

2021-07-05 18:07 UTC, AngeloCore commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
As i said, use `discord`

2021-07-05 18:07 UTC, AngeloCore commented on src/index.js
> +if (version.includes('(')) version = version.join('').split('(').pop().split('');
Then run `npm run format`

2021-07-05 18:09 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
I'll pass on that, and furthermore explained my point, if you simply wont go with it you're just breaching most common uses and cases, so you deny it :)

2021-07-05 18:09 UTC, GodyFromDiscord commented on src/index.js
> +if (version.includes('(')) version = version.join('').split('(').pop().split('');
Not needed, decreasing the amount of code lines and still works the same way.

2021-07-05 18:34 UTC, AngeloCore commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
Almost all discord.js video tutorials use `discord`. 
So please use `discord`

2021-07-05 18:37 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
First 3 videos I found lol https://imgur.com/a/DEWH197 along with the docs themselves, like I said deny the PR if you're so adamant of this.

2021-07-05 19:22 UTC, AngeloCore commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
Use `discord` or we will not merge!...

2021-07-05 19:23 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
You've switched it up now man. Just deny the Pull Request like I've said. Not a problem.

2021-07-05 19:24 UTC, AngeloCore commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
Can't you just replace `Discord` with `discord`?

2021-07-05 19:28 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
https://github.com/discord-buttons/discord-buttons/pull/115/commits/8823df6058e627ae32fb47db686b19d604128282

Done.

2021-07-05 19:28 UTC, GodyFromDiscord commented on README.md
> +const Discord = require('discord.js'); // Define the discord.js module
also done;

https://github.com/discord-buttons/discord-buttons/pull/115/commits/8a6f24034f6bdb8bef3db5a107eabbcb4c2ce3f5

2021-07-06 05:38 UTC, AngeloCore approved these changes

2021-07-06 05:39 UTC, AngeloCore commented on typings/index.d.ts
> +import Discord, {
??

2021-07-06 06:51 UTC, DeltaCoderr approved these changes
Seems good 👍🏻

2021-07-06 13:11 UTC, xHyroM approved these changes

2021-07-07 10:42 UTC, xHyroM requested changes
@GodyFromDiscord resolve conflicts

2021-07-07 14:04 UTC, GodyFromDiscord commented
The conflict has been resolved to fit the new main, but it wont show for some reason, you can see the commit here https://github.com/discord-buttons/discord-buttons/pull/115/commits/8f5ad26608f71fbe6520aae5ea8b52c8c653f10a

2021-07-07 14:05 UTC, GodyFromDiscord commented
Just merge it and change it if it keeps being weird

2021-07-07 18:56 UTC, xHyroM approved these changes

2021-07-07 19:15 UTC, Assassin-1234 approved these changes

2021-07-08 09:57 UTC, xHyroM commented
Merge?

2021-07-08 21:54 UTC, GodyFromDiscord commented
@AngeloCore

2021-07-09 17:13 UTC, merged

2021-07-09 17:14 UTC, DeltaCoderr commented
Thanks!