Fixed message edit issue
discord-buttons/discord-buttons pull request #118
Opened 2021-07-05 20:05 UTC by Tolfx

2021-07-05 20:06 UTC, Tolfx commented
![image](https://user-images.githubusercontent.com/57797792/124514380-2bf63a00-dddd-11eb-9ca3-426ec236d8f1.png)
![image](https://user-images.githubusercontent.com/57797792/124514435-4d572600-dddd-11eb-9d4e-b260eba91bad.png)

2021-07-06 13:10 UTC, xHyroM approved these changes

2021-07-06 13:34 UTC, MatrixSystemPVP commented on typings/index.d.ts
> +  send(content: APIMessageContentResolvable | (MessageOptions & { split?: false }) | MessageAdditions): Promise<this>;
Line already exist above

2021-07-06 14:30 UTC, MatrixSystemPVP requested changes
I think all 'MessageOptions' should be changed to 'ReplyOptions'.
And remove the one duplicated line.

(in the last commit)

2021-07-06 14:50 UTC, Tolfx commented
Replaced `MessageOptions` to `ReplyOptions`, which @MatrixSystemPVP suggested, kinda more logical if you think about it.

2021-07-07 08:39 UTC, AngeloCore approved these changes

2021-07-07 08:39 UTC, merged