bug fix
discord-buttons/discord-buttons pull request #129
Opened 2021-07-10 04:24 UTC by ZomoXYZ

I was unable to specify a Minimum value of 0 because `resolveMinValues` was being called by `MessageMenu.setMinValues` as `resolveMinValues(number)` while this function uses 2 values. This means the second value was `undefined`, and `0 || undefined` will return `undefined`, which is incorrect.

I'm not sure if this should be the final code, I just wanted to make something quick so I can finish my project.

2021-07-10 04:26 UTC, LoneWolf6969 commented
I fail to see why one has to set the minimum or maximum value to zero.

2021-07-10 04:29 UTC, ZomoXYZ commented
For example I'm making a role manager with a dropdown, and when a user removes all the roles they can they get this error 
![DiscordCanary_TCTwK7yTff](https://user-images.githubusercontent.com/11318718/125151653-6299c080-e10d-11eb-8da6-6ce87a99c288.png)

2021-07-14 17:08 UTC, Fox-Islam commented
Not sure if you were able to get past it for your use case @ZomoXYZ but I was just dealing with this now and I went around it by sending in a string `"0"` instead. Decided to check out this repo to open a PR to properly fix it, happy to see that there's a PR for it already, haha 😅 

I don't think the solution here is correct though - the default '1' from Discord's API docs are sensible, there shouldn't be any need to change that default for this use case. 
I think the more correct fix is to change it so that it allows `m1` to be [any of the values that the API allows](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure) (i.e. an integer between 0 and 25) instead of a weak truthy check
```javascript
resolveMinValues(m1, m2) {
    if (typeof m1 === 'number' && Number.isInteger(m1) && m1 >= 0 && m1 <= 25) {
        return m1;
    }
    return m2;
},
```
even just adding the `typeof` check would be a reasonable fix. It would allow `NaN` and `Infinity` to pass through but so does the current implementation 🤷

As for why one should be able to do something like this - select menus with nothing selected are valid, and deselecting everything is a valid operation in Discord. Doesn't make sense to reject the possibility of allowing that operation in this module.

2021-07-17 09:38 UTC, AngeloCore requested changes
check if `m1` exits and if `m1` is a number between 1 and 25, if is not make the same thing for `m2`
if `m1` and `m2` are undefined return 0

2021-07-28 18:20 UTC, AngeloCore commented
Inactive

2021-07-28 18:20 UTC, closed without merging