added setDisabled method to MessageMenu
discord-buttons/discord-buttons pull request #130
Opened 2021-07-11 03:59 UTC by ItsHisoka17

Pretty simple, discord API supported it so thought i should add it

2021-07-11 13:57 UTC, xHyroM approved these changes

2021-07-17 13:28 UTC, AngeloCore requested changes
add typing

2021-07-17 14:52 UTC, AngeloCore commented
We will use #138 instead

2021-07-17 14:52 UTC, closed without merging

2021-07-17 19:40 UTC, ItsHisoka17 commented
That's kinda rude, could've given me sometime to check github and add typings